name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}

          # The output files
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark